import { readFile, readdir, stat } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { pages } from '../src/data/pages.mjs';
import { home, SITE } from '../src/data/site.mjs';
const fail = [];
const assert = (condition,message) => { if (!condition) fail.push(message); };
const records = [home, ...pages, {slug:'confidentialite'}];
const titles = new Set(), descriptions = new Set(), images = new Set();
const routes = new Set(records.map(p=>`/${p.slug ? `${p.slug}/` : ''}`));
for (const page of records) {
  const file = `dist/${page.slug ? `${page.slug}/` : ''}index.html`;
  const html = await readFile(file,'utf8');
  const title = html.match(/<title>(.*?)<\/title>/s)?.[1];
  const desc = html.match(/<meta\s+name="description"\s+content="([^"]*)"/)?.[1];
  assert(title && !titles.has(title),`${file}: missing or duplicate title`); titles.add(title);
  assert(desc && !descriptions.has(desc),`${file}: missing or duplicate description`); descriptions.add(desc);
  assert((html.match(/<h1(?:\s|>)/g)||[]).length===1,`${file}: exactly one H1 required`);
  assert(html.includes(`href="${SITE}/${page.slug ? `${page.slug}/` : ''}"`),`${file}: canonical mismatch`);
  assert(html.includes('index, follow'),`${file}: indexability missing`);
  assert(html.includes('https://boxe-toulouse.com/'),`${file}: commercial destination missing`);
  const structured = [...html.matchAll(/<script type="application\/ld\+json"[^>]*>(.*?)<\/script>/gs)];
  assert(structured.length>0,`${file}: JSON-LD missing`);
  for(const match of structured) {
    const graph=JSON.parse(match[1])['@graph'];
    assert(!graph.some(n=>['SportsActivityLocation','LocalBusiness','SportsClub'].includes(n['@type'])),`${file}: invented physical club entity`);
    const faq=graph.find(n=>n['@type']==='FAQPage');
    if(page.faqs?.length) assert(faq?.mainEntity.length===page.faqs.length,`${file}: FAQ parity`);
  }
  for (const match of html.matchAll(/<img\b[^>]*>/g)) {
    assert(/alt=".+?"/.test(match[0]),`${file}: image alt missing`);
    assert(/width="\d+"/.test(match[0]) && /height="\d+"/.test(match[0]),`${file}: image dimensions missing`);
    const src=match[0].match(/src="([^"]+)"/)?.[1];
    if(src?.startsWith('/')) assert((await stat(`dist${src}`).catch(()=>null))?.isFile(),`${file}: missing image ${src}`);
  }
  for(const match of html.matchAll(/href="([^"#]+)(?:#[^"]*)?"/g)) {
    const href=match[1];
    if(href.startsWith('/') && !href.startsWith('//')) {
      const isFile=!!(await stat(`dist${href}`).catch(()=>null))?.isFile();
      assert(routes.has(href) || isFile,`${file}: broken internal link ${href}`);
    }
  }
  assert(!/notre salle (?:à|de) Blagnac|club situé à Blagnac|adresse[^<]{0,20}31700/.test(html),`${file}: false location`);
  assert(!/Co-Authored-By|made with (?:claude|openai)|generated by|créé par (?:Claude|ChatGPT)/i.test(html),`${file}: unwanted attribution`);
  const social=await readFile(`dist/social/${page.slug || 'accueil'}.png`);
  const hash=createHash('sha256').update(social).digest('hex');
  assert(!images.has(hash),`${file}: duplicate social image`); images.add(hash);
}
const sitemap=await readFile('dist/sitemap.xml','utf8');
const robots=await readFile('dist/robots.txt','utf8');
assert(robots.includes(`Sitemap: ${SITE}/sitemap.xml`) && !robots.includes('Disallow: /'), 'robots indexability');
for(const route of routes) assert(sitemap.includes(`<loc>${SITE}${route}</loc>`),`sitemap missing ${route}`);
assert((sitemap.match(/<loc>/g)||[]).length===routes.size,'sitemap route count');
assert((await readFile('dist/404.html','utf8').catch(()=>readFile('dist/404/index.html','utf8'))).includes('noindex, follow'),'404 must be noindex');
if(fail.length) { console.error(fail.join('\n')); process.exit(1); }
console.log(`Audit passed: ${records.length} indexable pages, unique metadata/social cards, canonical/sitemap, FAQs, images, internal links and truthful club location.`);
